/**
 * 6ékony Reklám – Reklámfelület katalógus
 * Forrás: https://6ekonyreklam.hu/reklamfeluleteink
 *
 * Az egyes helyszínek neve és leírása közvetlenül a weboldal city/type aloldalairól
 * származik (gyor/oriasplakatok, szekesfehervar/orias-feluletek, stb.).
 * GPS koordináták: az utcanevek / környezetleírások alapján közelítés.
 * Képek: ahol elérhető, a https://6ekonyreklam.hu/images/_korabbi-kepek/ könyvtárból;
 * a többi kültéri reklám jellegű Unsplash fotó.
 */

export type BillboardStatus = "free" | "booked";

export type Billboard = {
  id: string;
  name: string;
  city: string;
  type: string;
  size?: string;
  desc: string;
  price: number;
  lat: number;
  lng: number;
  ots: string;
  status: BillboardStatus;
  imageUrl: string;
};

/** react-leaflet panel + térkép marker adat */
export type MapBillboard = {
  id: string;
  title: string;
  city: string;
  lat: number;
  lng: number;
  ots: string;
  type: string;
  size?: string;
  price: number;
  imageUrl: string;
  status: BillboardStatus;
  desc: string;
};

/* ─── Képkönyvtár ───────────────────────────────────────────────────────────── */

/** Valódi 6ékony Reklám képek (https://6ekonyreklam.hu/images/_korabbi-kepek/) */
const IMG_6 = {
  mm_gabona:    "https://6ekonyreklam.hu/images/_korabbi-kepek/86e8e67edae9219d12d438efd5f5a939.jpg",
  mm_hild:      "https://6ekonyreklam.hu/images/_korabbi-kepek/4fcf9d660236ddb62c8456017158615a.jpg",
  mm_jozsef:    "https://6ekonyreklam.hu/images/_korabbi-kepek/e9ad9fee9d0bc73e0b2c055eb0b268ce.jpg",
};

/** Kültéri reklám jellegű Unsplash fotók (a többi felülethez) */
const IMG_U = {
  road1:   "https://images.unsplash.com/photo-1540960149937-f5b868f8f6d1?w=1200&q=85&auto=format&fit=crop",
  road2:   "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=1200&q=85&auto=format&fit=crop",
  road3:   "https://images.unsplash.com/photo-1573167243872-43c6433b9d40?w=1200&q=85&auto=format&fit=crop",
  road4:   "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=1200&q=85&auto=format&fit=crop",
  road5:   "https://images.unsplash.com/photo-1493238792000-8113da705763?w=1200&q=85&auto=format&fit=crop",
  city1:   "https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?w=1200&q=85&auto=format&fit=crop",
  city2:   "https://images.unsplash.com/photo-1480714378408-67cf0d13bc1b?w=1200&q=85&auto=format&fit=crop",
  city3:   "https://images.unsplash.com/photo-1519501025264-65ba15a82390?w=1200&q=85&auto=format&fit=crop",
  wall1:   "https://images.unsplash.com/photo-1520637836862-4d197d17c93a?w=1200&q=85&auto=format&fit=crop",
  wall2:   "https://images.unsplash.com/photo-1519999035996-1b52d73d8c9c?w=1200&q=85&auto=format&fit=crop",
  wall3:   "https://images.unsplash.com/photo-1544986581-efac024faf62?w=1200&q=85&auto=format&fit=crop",
  shop1:   "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1200&q=85&auto=format&fit=crop",
  shop2:   "https://images.unsplash.com/photo-1449824913935-59a10b8d2000?w=1200&q=85&auto=format&fit=crop",
  shop3:   "https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=1200&q=85&auto=format&fit=crop",
  lake1:   "https://images.unsplash.com/photo-1501854140801-50d01698950b?w=1200&q=85&auto=format&fit=crop",
  highway1:"https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1200&q=85&auto=format&fit=crop",
};

/* ─── Teljes hirdetőhely-adatbázis ─────────────────────────────────────────── */

export const billboards: Billboard[] = [

  /* ═══════════════════════════════ GYŐR ═══════════════════════════════════════ */

  // — Óriásplakátok —
  {
    id: "GY-OP-01",
    name: "Győri Árkád parkoló bejárat",
    city: "Győr",
    type: "Óriásplakát",
    size: "504×238 cm",
    desc: "Az Árkád alsó parkolójának bejáratánál. Pár percre a belvárostól. Közelben: Jysk, Hotel Famulus, Colosseum Fitness.",
    price: 55_000,
    lat: 47.6742, lng: 17.6577,
    ots: "38 000",
    status: "free",
    imageUrl: IMG_U.road1,
  },
  {
    id: "GY-OP-02",
    name: "Árkád parkolóval szemben",
    city: "Győr",
    type: "Óriásplakát",
    size: "504×238 cm",
    desc: "Közkedvelt, frekventált helyen, az Árkád parkolóval szemben.",
    price: 52_000,
    lat: 47.6737, lng: 17.6569,
    ots: "35 000",
    status: "free",
    imageUrl: IMG_U.road2,
  },
  {
    id: "GY-OP-03",
    name: "Árkád parkoló – molinó felület",
    city: "Győr",
    type: "Óriásplakát",
    size: "504×238 cm",
    desc: "Az Árkád parkolónál. Molinó reklámanyag helyezhető ki.",
    price: 48_000,
    lat: 47.6738, lng: 17.6585,
    ots: "33 000",
    status: "booked",
    imageUrl: IMG_U.shop1,
  },
  {
    id: "GY-OP-04",
    name: "ETO Park – Mártírok útja",
    city: "Győr",
    type: "Óriásplakát",
    size: "504×238 cm",
    desc: "Az ETO Parknál, az 1-es számú forgalmas főút mellett. Cutlet Fitness, Okmányiroda, Xantus János Állatkert, Audi Aréna közelében.",
    price: 62_000,
    lat: 47.6879, lng: 17.6502,
    ots: "45 000",
    status: "free",
    imageUrl: IMG_U.road3,
  },
  {
    id: "GY-OP-05",
    name: "81-es főút – Pér bevezető",
    city: "Győr",
    type: "Óriásplakát",
    size: "504×238 cm",
    desc: "A 81-es számú főút mellett, Pér irányából a városba bevezető úton. Közelben vendéglő és benzinkút.",
    price: 44_000,
    lat: 47.7108, lng: 17.6818,
    ots: "28 000",
    status: "free",
    imageUrl: IMG_U.highway1,
  },
  {
    id: "GY-OP-06",
    name: "83-as főút – Nádorvárosi temető",
    city: "Győr",
    type: "Óriásplakát",
    size: "504×238 cm",
    desc: "A 83-as számú főút mellett. Nádorvárosi temető, Szentlélek-templom szomszédságában. Tesco, McDonalds, Family Center elérési útján.",
    price: 58_000,
    lat: 47.6622, lng: 17.6808,
    ots: "42 000",
    status: "free",
    imageUrl: IMG_U.road4,
  },
  {
    id: "GY-OP-07",
    name: "83-as út – Tesco irányába",
    city: "Győr",
    type: "Óriásplakát",
    size: "504×238 cm",
    desc: "A 83-as út egyik legforgalmasabb szakasza. Tesco, McDonalds, Praktiker körforgalom, kis Tesco, Lidl, Hatvani Gumiszervíz közelében.",
    price: 56_000,
    lat: 47.6640, lng: 17.6850,
    ots: "40 000",
    status: "free",
    imageUrl: IMG_U.road5,
  },
  {
    id: "GY-OP-08",
    name: "Marcalváros – forgalmas kereszteződés",
    city: "Győr",
    type: "Óriásplakát",
    size: "504×238 cm",
    desc: "Marcalváros egyik forgalmas lámpás kereszteződésénél. Közelben: Tesco, gyógyszertár, OTP Bank, Spar, étterem.",
    price: 54_000,
    lat: 47.6756, lng: 17.6152,
    ots: "36 000",
    status: "free",
    imageUrl: IMG_U.city1,
  },
  {
    id: "GY-OP-09",
    name: "83-as út – autópálya közelében",
    city: "Győr",
    type: "Óriásplakát",
    size: "504×238 cm",
    desc: "A 83-as út egyik legforgalmasabb szakasza, az M1-es autópálya közelében.",
    price: 50_000,
    lat: 47.6548, lng: 17.6990,
    ots: "44 000",
    status: "free",
    imageUrl: IMG_U.highway1,
  },
  {
    id: "GY-OP-10",
    name: "Szent Imre út – József Attila körforgalom",
    city: "Győr",
    type: "Óriásplakát",
    size: "504×238 cm",
    desc: "A Szent Imre út – József Attila úti körforgalomban. Zsúfolt környék, a város egyik legforgalmasabb ki- és bejáró útszakasza.",
    price: 60_000,
    lat: 47.6888, lng: 17.6453,
    ots: "48 000",
    status: "free",
    imageUrl: IMG_U.road1,
  },
  {
    id: "GY-OP-11",
    name: "82-es főút – körforgalom (cukrászda)",
    city: "Győr",
    type: "Óriásplakát",
    size: "504×238 cm",
    desc: "A 82-es főút keresztezi a Szent Imre út–József Attila út körforgalmát. Benzinkút, cukrászda közelében.",
    price: 52_000,
    lat: 47.6893, lng: 17.6440,
    ots: "38 000",
    status: "booked",
    imageUrl: IMG_U.road2,
  },
  {
    id: "GY-OP-12",
    name: "Galántai út – Vámosszabadi bevezető",
    city: "Győr",
    type: "Óriásplakát",
    size: "504×238 cm",
    desc: "A Galántai úton, Vámosszabadi felöl érkezőknek. Bácsai úti kereszteződés, Csülök Sarok Étterem, Árkád Bevásárlóközpont irányában.",
    price: 46_000,
    lat: 47.7210, lng: 17.6548,
    ots: "26 000",
    status: "free",
    imageUrl: IMG_U.shop2,
  },

  // — Óriás felületek (Győr) —
  {
    id: "GY-OF-01",
    name: "Győr – Óriás tábla 10×15 m",
    city: "Győr",
    type: "Óriás felület",
    size: "10×15 m",
    desc: "10×15 méteres óriás reklámfelület Győr frekventált pontján.",
    price: 120_000,
    lat: 47.6830, lng: 17.6400,
    ots: "52 000",
    status: "free",
    imageUrl: IMG_U.wall1,
  },
  {
    id: "GY-OF-02",
    name: "Győr – Óriás tábla 4×10 m",
    city: "Győr",
    type: "Óriás felület",
    size: "4×10 m",
    desc: "4×10 méteres óriás reklámfelület Győrben.",
    price: 75_000,
    lat: 47.6810, lng: 17.6470,
    ots: "40 000",
    status: "free",
    imageUrl: IMG_U.wall2,
  },
  {
    id: "GY-OF-03",
    name: "Győr – Épülethomlokzat 8×10 m",
    city: "Győr",
    type: "Óriás felület",
    size: "8×10 m",
    desc: "8×10 méteres épülethomlokzat-hirdetés Győrben.",
    price: 95_000,
    lat: 47.6795, lng: 17.6508,
    ots: "45 000",
    status: "free",
    imageUrl: IMG_U.wall3,
  },
  {
    id: "GY-OF-04",
    name: "Győr – Épülethomlokzat 8×10 m (B)",
    city: "Győr",
    type: "Óriás felület",
    size: "8×10 m",
    desc: "Második 8×10 méteres épülethomlokzat Győrben.",
    price: 92_000,
    lat: 47.6798, lng: 17.6512,
    ots: "43 000",
    status: "booked",
    imageUrl: IMG_U.wall1,
  },
  {
    id: "GY-OF-05",
    name: "Győr – Tábla 5×7 m",
    city: "Győr",
    type: "Óriás felület",
    size: "5×7 m",
    desc: "5×7 méteres szabadtéri reklámfelület Győrben.",
    price: 68_000,
    lat: 47.6760, lng: 17.6555,
    ots: "37 000",
    status: "free",
    imageUrl: IMG_U.shop3,
  },

  /* ═══════════════════════════════ MOSONMAGYARÓVÁR ════════════════════════════ */

  {
    id: "MM-OP-01",
    name: "Gabona rakpart – Camping mellett",
    city: "Mosonmagyaróvár",
    type: "Óriásplakát",
    size: "504×238 cm",
    desc: "A Gabona rakparton, a Camping szomszédságában. Lajta-parti frekventált pont.",
    price: 40_000,
    lat: 47.8695, lng: 17.2580,
    ots: "22 000",
    status: "free",
    imageUrl: IMG_6.mm_gabona,
  },
  {
    id: "MM-OP-02",
    name: "Hild tér – Vasútállomás",
    city: "Mosonmagyaróvár",
    type: "Óriásplakát",
    size: "504×238 cm",
    desc: "A Hild téren, a vasútállomás közelében. Nagy gyalogos- és gépjárműforgalom.",
    price: 42_000,
    lat: 47.8690, lng: 17.2620,
    ots: "24 000",
    status: "free",
    imageUrl: IMG_6.mm_hild,
  },
  {
    id: "MM-OP-03",
    name: "József Attila utca – 1. számú főút",
    city: "Mosonmagyaróvár",
    type: "Óriásplakát",
    size: "504×238 cm",
    desc: "A József Attila utcán, az 1-es számú főút mentén. Bevezető szakasz, magas forgalom.",
    price: 44_000,
    lat: 47.8712, lng: 17.2662,
    ots: "28 000",
    status: "free",
    imageUrl: IMG_6.mm_jozsef,
  },
  {
    id: "MM-KF-01",
    name: "Mosonmagyaróvár – Kis felület (Fő tér)",
    city: "Mosonmagyaróvár",
    type: "Kis felület",
    desc: "Egyedi kültéri reklámfelület a Fő tér közelében. Szemmagasságban, elkülönül a reklámzajtól.",
    price: 28_000,
    lat: 47.8726, lng: 17.2684,
    ots: "18 000",
    status: "free",
    imageUrl: IMG_U.city2,
  },
  {
    id: "MM-KF-02",
    name: "Mosonmagyaróvár – Kis felület (Pozsonyi út)",
    city: "Mosonmagyaróvár",
    type: "Kis felület",
    desc: "Egyedi kültéri reklámfelület a Pozsonyi út mentén. Helyszíngarancia.",
    price: 26_000,
    lat: 47.8742, lng: 17.2710,
    ots: "16 000",
    status: "free",
    imageUrl: IMG_U.city3,
  },
  {
    id: "MM-KF-03",
    name: "Mosonmagyaróvár – Kis felület (Lajta-híd)",
    city: "Mosonmagyaróvár",
    type: "Kis felület",
    desc: "Szemmagasságú kültéri reklámfelület a Lajta-híd közelében.",
    price: 25_000,
    lat: 47.8708, lng: 17.2640,
    ots: "15 000",
    status: "booked",
    imageUrl: IMG_U.road1,
  },

  /* ═══════════════════════════════ KECSKEMÉT ══════════════════════════════════ */

  {
    id: "KC-OP-01",
    name: "Izsáki út (52-es) – bevezető",
    city: "Kecskemét",
    type: "Óriásplakát",
    size: "504×238 cm",
    desc: "Az 52-es (Izsáki) főút, a városba tartó egyik legfontosabb bevezető. Közelben: KFC, McDonald's, gimnázium, egyetem, stadion.",
    price: 58_000,
    lat: 46.9175, lng: 19.6760,
    ots: "41 000",
    status: "free",
    imageUrl: IMG_U.road3,
  },
  {
    id: "KC-OP-02",
    name: "Belváros – Malom Center",
    city: "Kecskemét",
    type: "Óriásplakát",
    size: "504×238 cm",
    desc: "Kecskemét belvárosában, a Malom Mozi és a Malom Center szomszédságában. Bank, galéria, óvoda, borház közelében.",
    price: 60_000,
    lat: 46.9064, lng: 19.6918,
    ots: "38 000",
    status: "free",
    imageUrl: IMG_U.city1,
  },
  {
    id: "KC-OP-03",
    name: "5-ös út – Kórház utca (Erzsébetváros)",
    city: "Kecskemét",
    type: "Óriásplakát",
    size: "504×238 cm",
    desc: "Kecskemét belvárosában, Erzsébetváros részén, az 5-ös út–Kórház utca körforgalomban. Benzinkút, focipálya, gumiszerviz közelében.",
    price: 54_000,
    lat: 46.9022, lng: 19.6982,
    ots: "35 000",
    status: "free",
    imageUrl: IMG_U.road4,
  },
  {
    id: "KC-OP-04",
    name: "Könyves Kálmán körút – Szent László körút",
    city: "Kecskemét",
    type: "Óriásplakát",
    size: "504×238 cm",
    desc: "A Könyves Kálmán körúton, a Szent László körút irányába. Cégek, autókereskedések, éttermek közelében.",
    price: 52_000,
    lat: 46.9145, lng: 19.7010,
    ots: "32 000",
    status: "booked",
    imageUrl: IMG_U.road5,
  },
  {
    id: "KC-KF-01",
    name: "Kecskemét – Kis felület (belváros)",
    city: "Kecskemét",
    type: "Kis felület",
    desc: "Egyedi kültéri reklámfelület Kecskemét belvárosában. Szemmagasságban, magas kontaktszám.",
    price: 30_000,
    lat: 46.9090, lng: 19.6950,
    ots: "20 000",
    status: "free",
    imageUrl: IMG_U.city2,
  },
  {
    id: "KC-KF-02",
    name: "Kecskemét – Kis felület (kereskedelmi negyed)",
    city: "Kecskemét",
    type: "Kis felület",
    desc: "Kis kültéri reklámfelület a kereskedelmi negyedben. Helyszíngarancia.",
    price: 28_000,
    lat: 46.9110, lng: 19.6970,
    ots: "18 000",
    status: "free",
    imageUrl: IMG_U.shop1,
  },

  /* ═══════════════════════════════ SZÉKESFEHÉRVÁR ═════════════════════════════ */

  // — Óriásplakátok —
  {
    id: "SF-OP-01",
    name: "Új Csóri út – centrum felé (bal)",
    city: "Székesfehérvár",
    type: "Óriásplakát",
    size: "504×238 cm",
    desc: "Az Új Csóri úton, bal kéz felöl a centrum irányába haladóknak.",
    price: 52_000,
    lat: 47.1820, lng: 18.3898,
    ots: "36 000",
    status: "free",
    imageUrl: IMG_U.road1,
  },
  {
    id: "SF-OP-02",
    name: "Új Csóri út – LIDL közelében (jobb)",
    city: "Székesfehérvár",
    type: "Óriásplakát",
    size: "504×238 cm",
    desc: "Az Új Csóri úton, jobb oldalon, a LIDL közvetlen közelében.",
    price: 50_000,
    lat: 47.1813, lng: 18.3890,
    ots: "34 000",
    status: "free",
    imageUrl: IMG_U.shop2,
  },
  {
    id: "SF-OP-03",
    name: "Palotai úti körforgalom (Csóri út)",
    city: "Székesfehérvár",
    type: "Óriásplakát",
    size: "504×238 cm",
    desc: "Külvárosban, a Csóri úton, a Palotai úti körforgalomban. A 7-es és 8-as főutak találkozásánál, LIDL bevásárlóközpont mellett.",
    price: 55_000,
    lat: 47.1800, lng: 18.3870,
    ots: "40 000",
    status: "free",
    imageUrl: IMG_U.road2,
  },
  {
    id: "SF-OP-04",
    name: "Új Csóri úti LIDL közelében",
    city: "Székesfehérvár",
    type: "Óriásplakát",
    size: "504×238 cm",
    desc: "Az Új Csóri úti LIDL közelében elhelyezett hirdetőfelület.",
    price: 48_000,
    lat: 47.1825, lng: 18.3905,
    ots: "32 000",
    status: "booked",
    imageUrl: IMG_U.road3,
  },
  {
    id: "SF-OP-05",
    name: "Új Csóri úti LIDL körforgalom – centrum",
    city: "Székesfehérvár",
    type: "Óriásplakát",
    size: "504×238 cm",
    desc: "Az Új Csóri úti LIDL körforgalom közelében, a centrum irányába.",
    price: 50_000,
    lat: 47.1808, lng: 18.3882,
    ots: "35 000",
    status: "free",
    imageUrl: IMG_U.road4,
  },
  {
    id: "SF-OP-06",
    name: "Palotai út – Kelemen Béla út (Koronás Park)",
    city: "Székesfehérvár",
    type: "Óriásplakát",
    size: "504×238 cm",
    desc: "A Palotai út–Kelemen Béla út kereszteződésénél, a Koronás Park és a Rózsaliget közelében. Étterem, vendéglő, pizzázó a környéken.",
    price: 56_000,
    lat: 47.1952, lng: 18.4102,
    ots: "38 000",
    status: "free",
    imageUrl: IMG_U.city1,
  },
  {
    id: "SF-OP-07",
    name: "Új Csóri út – Várpalota felőli, felső",
    city: "Székesfehérvár",
    type: "Óriásplakát",
    size: "504×238 cm",
    desc: "Várpalota irányából érkező forgalmat fogadó felső elhelyezésű óriásplakát az Új Csóri úton.",
    price: 46_000,
    lat: 47.1790, lng: 18.3860,
    ots: "30 000",
    status: "free",
    imageUrl: IMG_U.highway1,
  },
  {
    id: "SF-OP-08",
    name: "Szent Flórián körút – Tesco (McDonald's)",
    city: "Székesfehérvár",
    type: "Óriásplakát",
    size: "504×238 cm",
    desc: "A Szent Flórián körúton, a TESCO-nál, a város irányába. McDonald's és benzinkút a közelben.",
    price: 58_000,
    lat: 47.2060, lng: 18.4320,
    ots: "44 000",
    status: "free",
    imageUrl: IMG_U.road5,
  },
  {
    id: "SF-OP-09",
    name: "Széchenyi út – Auchan irányába",
    city: "Székesfehérvár",
    type: "Óriásplakát",
    size: "504×238 cm",
    desc: "A Széchenyi úton, az Auchan bevásárlóközpont irányába tartó forgalomnak.",
    price: 54_000,
    lat: 47.1882, lng: 18.4140,
    ots: "42 000",
    status: "free",
    imageUrl: IMG_U.shop3,
  },

  // — Óriás felületek (Székesfehérvár) —
  {
    id: "SF-OF-01",
    name: "Várkörút – Vasalóház (5×5 m)",
    city: "Székesfehérvár",
    type: "Óriás felület",
    size: "5×5 m",
    desc: "A Várkörúton, a Vasalóházon elhelyezett 5×5 méteres épülethomlokzat-hirdetés.",
    price: 70_000,
    lat: 47.1942, lng: 18.4080,
    ots: "40 000",
    status: "free",
    imageUrl: IMG_U.wall1,
  },
  {
    id: "SF-OF-02",
    name: "Jancsár utca – SPAR (10×20 m)",
    city: "Székesfehérvár",
    type: "Óriás felület",
    size: "10×20 m",
    desc: "A Jancsár utcában, SPAR, Horgászáruház, szépségszalon, múzeum, cukrászda és pubok közelében.",
    price: 140_000,
    lat: 47.1975, lng: 18.4155,
    ots: "55 000",
    status: "free",
    imageUrl: IMG_U.wall2,
  },
  {
    id: "SF-OF-03",
    name: "Budai út – épülethomlokzat (10×20 m)",
    city: "Székesfehérvár",
    type: "Óriás felület",
    size: "10×20 m",
    desc: "A Budai úton, tízemeletes épület homlokzatán. OBI, INTERSPÁR, McDonald's pár percre. Méret: 10×20 m.",
    price: 160_000,
    lat: 47.2005, lng: 18.4175,
    ots: "60 000",
    status: "free",
    imageUrl: IMG_U.wall3,
  },
  {
    id: "SF-OF-04",
    name: "Selyem utca – Alba Pláza (10×10 m)",
    city: "Székesfehérvár",
    type: "Óriás felület",
    size: "10×10 m",
    desc: "A Selyem utcán, az Alba Pláza közvetlen közelében. Buszmegálló, piactér, McDonald's, Katedra szomszédságában.",
    price: 110_000,
    lat: 47.1920, lng: 18.4100,
    ots: "52 000",
    status: "free",
    imageUrl: IMG_U.city2,
  },
  {
    id: "SF-OF-05",
    name: "Horváth István út – Prohászka út (5×5 m)",
    city: "Székesfehérvár",
    type: "Óriás felület",
    size: "5×5 m",
    desc: "A Horváth István út–Prohászka út kereszteződésénél elhelyezett felső reklámfelület.",
    price: 65_000,
    lat: 47.1962, lng: 18.4065,
    ots: "36 000",
    status: "booked",
    imageUrl: IMG_U.road2,
  },
  {
    id: "SF-OF-06",
    name: "Csóri út – Palotai körforgalom (5×5 m)",
    city: "Székesfehérvár",
    type: "Óriás felület",
    size: "5×5 m",
    desc: "A Csóri úton, a Palotai úti körforgalomban, a 7-es és 8-as főutak találkozásánál. 5×5 méter.",
    price: 68_000,
    lat: 47.1795, lng: 18.3865,
    ots: "38 000",
    status: "free",
    imageUrl: IMG_U.shop1,
  },
  {
    id: "SF-OF-07",
    name: "Székesfehérvár – Óriásfelület 10×15 m",
    city: "Székesfehérvár",
    type: "Óriás felület",
    size: "10×15 m",
    desc: "10×15 méteres óriás reklámfelület Székesfehérvár frekventált pontján.",
    price: 130_000,
    lat: 47.1990, lng: 18.4200,
    ots: "58 000",
    status: "free",
    imageUrl: IMG_U.wall1,
  },

  /* ═══════════════════════════════ SZOLNOK ════════════════════════════════════ */

  {
    id: "SN-OF-01",
    name: "Szolnok – Óriás felület (centrum)",
    city: "Szolnok",
    type: "Óriás felület",
    desc: "Óriás méretű hirdetőfelület Szolnok centrumában, nagy forgalmú útvonalon.",
    price: 85_000,
    lat: 47.1755, lng: 20.1963,
    ots: "38 000",
    status: "free",
    imageUrl: IMG_U.wall2,
  },
  {
    id: "SN-KF-01",
    name: "Szolnok – Kis felület (Kossuth tér)",
    city: "Szolnok",
    type: "Kis felület",
    desc: "Egyedi kültéri reklámfelület a Kossuth tér közelében. Szemmagasság, magas kontaktszám.",
    price: 30_000,
    lat: 47.1760, lng: 20.1985,
    ots: "22 000",
    status: "free",
    imageUrl: IMG_U.city1,
  },
  {
    id: "SN-KF-02",
    name: "Szolnok – Kis felület (Szapáry út)",
    city: "Szolnok",
    type: "Kis felület",
    desc: "Kültéri reklámfelület a Szapáry út mentén. Helyszíngarancia.",
    price: 28_000,
    lat: 47.1750, lng: 20.1940,
    ots: "20 000",
    status: "free",
    imageUrl: IMG_U.city3,
  },
  {
    id: "SN-KF-03",
    name: "Szolnok – Kis felület (Budapesti út)",
    city: "Szolnok",
    type: "Kis felület",
    desc: "Kis kültéri reklámfelület a Budapesti út mentén, bevezető szakaszon.",
    price: 32_000,
    lat: 47.1720, lng: 20.1900,
    ots: "25 000",
    status: "booked",
    imageUrl: IMG_U.highway1,
  },
  {
    id: "SN-KF-04",
    name: "Szolnok – Kis felület (Tósziget)",
    city: "Szolnok",
    type: "Kis felület",
    desc: "Kültéri reklámfelület a Tósziget szabadidős övezet közelében.",
    price: 26_000,
    lat: 47.1790, lng: 20.2010,
    ots: "18 000",
    status: "free",
    imageUrl: IMG_U.lake1,
  },
  {
    id: "SN-KF-05",
    name: "Szolnok – Kis felület (Ady Endre út)",
    city: "Szolnok",
    type: "Kis felület",
    desc: "Egyedi kültéri felület az Ady Endre úton, elkülönül a reklámzajtól.",
    price: 27_000,
    lat: 47.1730, lng: 20.2040,
    ots: "19 000",
    status: "free",
    imageUrl: IMG_U.road1,
  },

  /* ═══════════════════════════════ VELENCE ════════════════════════════════════ */

  {
    id: "VL-KF-01",
    name: "Velence – Velencei tó út",
    city: "Velence",
    type: "Kis felület",
    desc: "Kültéri reklámfelület a Velencei tó partján, a főút mentén. Kirándulók és átmenő forgalom.",
    price: 32_000,
    lat: 47.2348, lng: 18.6578,
    ots: "20 000",
    status: "free",
    imageUrl: IMG_U.lake1,
  },
  {
    id: "VL-KF-02",
    name: "Velence – Alagi út",
    city: "Velence",
    type: "Kis felület",
    desc: "Az Alagi úton elhelyezett egyedi kültéri reklámfelület. Helyszíngarancia.",
    price: 28_000,
    lat: 47.2352, lng: 18.6590,
    ots: "16 000",
    status: "free",
    imageUrl: IMG_U.road2,
  },
  {
    id: "VL-KF-03",
    name: "Velence – Sukorói úti körforgalom",
    city: "Velence",
    type: "Kis felület",
    desc: "A Sukorói úti körforgalomnál, a Velencei-tó turisztikai övezetének bejáratán.",
    price: 30_000,
    lat: 47.2338, lng: 18.6562,
    ots: "18 000",
    status: "free",
    imageUrl: IMG_U.road3,
  },
  {
    id: "VL-KF-04",
    name: "Velence – Gárdonyi Géza utca",
    city: "Velence",
    type: "Kis felület",
    desc: "A Gárdonyi Géza utcán, a falu centrumában.",
    price: 24_000,
    lat: 47.2340, lng: 18.6610,
    ots: "14 000",
    status: "booked",
    imageUrl: IMG_U.city2,
  },
  {
    id: "VL-KF-05",
    name: "Velence – Pázmány Péter utca",
    city: "Velence",
    type: "Kis felület",
    desc: "A Pázmány Péter utcán elhelyezett egyedi kültéri felület.",
    price: 22_000,
    lat: 47.2325, lng: 18.6600,
    ots: "13 000",
    status: "free",
    imageUrl: IMG_U.shop1,
  },
  {
    id: "VL-KF-06",
    name: "Velence – Strand bejárat",
    city: "Velence",
    type: "Kis felület",
    desc: "A Velencei-tó strandhoz vezető sétányon. Nyáron kiugróan magas látogatóforgalom.",
    price: 35_000,
    lat: 47.2355, lng: 18.6550,
    ots: "26 000",
    status: "free",
    imageUrl: IMG_U.lake1,
  },
];

/* ─── Segédfüggvények ───────────────────────────────────────────────────────── */

export function toMapBillboard(b: Billboard): MapBillboard {
  return {
    id: b.id,
    title: b.name,
    city: b.city,
    lat: b.lat,
    lng: b.lng,
    ots: b.ots,
    type: b.type,
    size: b.size,
    price: b.price,
    imageUrl: b.imageUrl,
    status: b.status,
    desc: b.desc,
  };
}

export const mapBillboards: MapBillboard[] = billboards.map(toMapBillboard);

export const CITIES = [
  "Győr",
  "Mosonmagyaróvár",
  "Kecskemét",
  "Székesfehérvár",
  "Szolnok",
  "Velence",
] as const;

export type SurfaceFilter = "all" | "oriasplakat" | "orias" | "kis";

export function filterBillboards(
  items: Billboard[],
  typeFilter: SurfaceFilter,
  city: string
): Billboard[] {
  return items.filter((b) => {
    if (city !== "all" && b.city !== city) return false;
    if (typeFilter === "all") return true;
    const t = b.type.toLowerCase();
    if (typeFilter === "oriasplakat") return t.includes("óriásplakát");
    if (typeFilter === "orias") return t.includes("óriás felület");
    if (typeFilter === "kis") return t.includes("kis");
    return true;
  });
}
